sonar.projectKey=Saif-3003_employeeApp-SonarQube
sonar.organization=saif-3003
sonar.projectName=Employee Management API

sonar.sources=src,client/src
sonar.tests=test

sonar.exclusions=**/node_modules/**,**/coverage/**,client/build/**,client/public/**
